---
- name: "Download Helm installation script"
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  args:
    creates: get_helm.sh

- name: "Make Helm script executable"
  ansible.builtin.file:
    path: get_helm.sh
    mode: '0700'

- name: "Install Helm using official script"
  ansible.builtin.shell: ./get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: "Clean up installation script"
  ansible.builtin.file:
    path: get_helm.sh
    state: absent

- name: "Verify Helm installation"
  ansible.builtin.shell: helm version --short
  register: helm_version
  changed_when: false

- name: "Display Helm version"
  ansible.builtin.debug:
    msg: "Helm version: {{ helm_version.stdout }}"