---
- name: "Install kubernetes Python library"
  ansible.builtin.pip:
    name: kubernetes
    state: present

- name: "Create Jenkins namespace"
  kubernetes.core.k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present

- name: "Create Jenkins ServiceAccount"
  kubernetes.core.k8s:
    name: jenkins
    namespace: jenkins
    api_version: v1
    kind: ServiceAccount
    state: present

- name: "Create Jenkins Role"
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: jenkins-role
        namespace: jenkins
      rules:
      - apiGroups: [""]
        resources: ["pods", "pods/log", "services", "secrets", "configmaps"]
        verbs: ["get", "list", "watch", "create", "update", "delete"]
      - apiGroups: ["apps"]
        resources: ["deployments", "statefulsets", "replicasets"]
        verbs: ["get", "list", "watch", "create", "update", "delete"]
    state: present

- name: "Create Jenkins RoleBinding"
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: jenkins-rolebinding
        namespace: jenkins
      subjects:
      - kind: ServiceAccount
        name: jenkins
        namespace: jenkins
      roleRef:
        kind: Role
        name: jenkins-role
        apiGroup: rbac.authorization.k8s.io
    state: present

- name: "Create Jenkins ServiceAccount token secret"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: jenkins-sa-token
        namespace: jenkins
        annotations:
          kubernetes.io/service-account.name: jenkins
      type: kubernetes.io/service-account-token
    state: present