---
- name: "Install Jenkins CLI dependencies"
  ansible.builtin.apt:
    name:
      - curl
      - wget
    state: present

- name: "Wait for Jenkins to be ready"
  ansible.builtin.wait_for:
    port: 8080
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 120

- name: "Get Jenkins CLI jar"
  ansible.builtin.get_url:
    url: "http://{{ ansible_default_ipv4.address }}:8080/jnlpJars/jenkins-cli.jar"
    dest: /tmp/jenkins-cli.jar
    mode: '0644'

- name: "Test Jenkins CLI connection"
  ansible.builtin.shell: |
    java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_default_ipv4.address }}:8080 -auth admin:{{ jenkins_initial_password.stdout }} version
  register: jenkins_cli_test
  failed_when: false

- name: "Display Jenkins CLI test result"
  ansible.builtin.debug:
    msg: |
      Jenkins CLI test result:
      {{ jenkins_cli_test.stdout }}
      Return code: {{ jenkins_cli_test.rc }}

- name: "List existing Jenkins jobs"
  ansible.builtin.shell: |
    java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_default_ipv4.address }}:8080 -auth admin:{{ jenkins_initial_password.stdout }} list-jobs
  register: existing_jobs
  failed_when: false

- name: "Display existing jobs"
  ansible.builtin.debug:
    msg: |
      Existing Jenkins jobs:
      {{ existing_jobs.stdout }}

- name: "Create Jenkins pipeline script"
  ansible.builtin.copy:
    dest: /tmp/simple-pod-pipeline.groovy
    content: |
      pipeline {
          agent any
          
          environment {
              KUBECONFIG = '/var/jenkins_home/.kube/config'
          }
          
          stages {
              stage('Checkout') {
                  steps {
                      echo 'Starting pipeline for simple pod deployment'
                  }
              }
              
              stage('Deploy Simple Pod') {
                  steps {
                      script {
                          sh '''
                              cat <<EOF | kubectl apply -f -
                              apiVersion: v1
                              kind: Pod
                              metadata:
                                name: simple-test-pod
                                labels:
                                  app: simple-test
                              spec:
                                containers:
                                - name: nginx
                                  image: nginx:latest
                                  ports:
                                  - containerPort: 80
                                  resources:
                                    requests:
                                      memory: "64Mi"
                                      cpu: "250m"
                                    limits:
                                      memory: "128Mi"
                                      cpu: "500m"
                              EOF
                          '''
                      }
                  }
              }
              
              stage('Verify Deployment') {
                  steps {
                      sh '''
                          echo "Waiting for pod to be ready..."
                          kubectl wait --for=condition=Ready pod/simple-test-pod --timeout=60s
                          echo "Pod status:"
                          kubectl get pod simple-test-pod
                          echo "Pod details:"
                          kubectl describe pod simple-test-pod
                      '''
                  }
              }
              
              stage('Test Pod') {
                  steps {
                      sh '''
                          echo "Testing pod connectivity..."
                          kubectl exec simple-test-pod -- curl -f http://localhost:80 || echo "Pod is running but curl test failed"
                      '''
                  }
              }
          }
          
          post {
              always {
                  echo 'Pipeline completed'
              }
              success {
                  echo 'Pod deployment successful!'
              }
              failure {
                  echo 'Pod deployment failed!'
                  sh 'kubectl get pods | grep simple-test-pod || echo "Pod not found"'
              }
          }
      }

- name: "Get Jenkins initial admin password"
  ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial_password
  changed_when: false

- name: "Display Jenkins initial admin password"
  ansible.builtin.debug:
    msg: "Jenkins initial admin password: {{ jenkins_initial_password.stdout }}"

- name: "Create Jenkins job using REST API"
  ansible.builtin.uri:
    url: "http://{{ ansible_default_ipv4.address }}:8080/createItem?name=simple-pod-deployment"
    method: POST
    user: admin
    password: "{{ jenkins_initial_password.stdout }}"
    headers:
      Content-Type: "application/xml"
    body: |
      <?xml version='1.1' encoding='UTF-8'?>
      <flow-definition plugin="workflow-job@2.45">
        <description>Simple pod deployment pipeline</description>
        <keepDependencies>false</keepDependencies>
        <properties/>
        <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.92">
          <script>
      pipeline {
          agent any
          
          environment {
              KUBECONFIG = '/var/jenkins_home/.kube/config'
          }
          
          stages {
              stage('Checkout') {
                  steps {
                      echo 'Starting pipeline for simple pod deployment'
                  }
              }
              
              stage('Deploy Simple Pod') {
                  steps {
                      script {
                          sh '''
                              cat <<EOF | kubectl apply -f -
                              apiVersion: v1
                              kind: Pod
                              metadata:
                                name: simple-test-pod
                                labels:
                                  app: simple-test
                              spec:
                                containers:
                                - name: nginx
                                  image: nginx:latest
                                  ports:
                                  - containerPort: 80
                                  resources:
                                    requests:
                                      memory: "64Mi"
                                      cpu: "250m"
                                    limits:
                                      memory: "128Mi"
                                      cpu: "500m"
                              EOF
                          '''
                      }
                  }
              }
              
              stage('Verify Deployment') {
                  steps {
                      sh '''
                          echo "Waiting for pod to be ready..."
                          kubectl wait --for=condition=Ready pod/simple-test-pod --timeout=60s
                          echo "Pod status:"
                          kubectl get pod simple-test-pod
                          echo "Pod details:"
                          kubectl describe pod simple-test-pod
                      '''
                  }
              }
              
              stage('Test Pod') {
                  steps {
                      sh '''
                          echo "Testing pod connectivity..."
                          kubectl exec simple-test-pod -- curl -f http://localhost:80 || echo "Pod is running but curl test failed"
                      '''
                  }
              }
          }
          
          post {
              always {
                  echo 'Pipeline completed'
              }
              success {
                  echo 'Pod deployment successful!'
              }
              failure {
                  echo 'Pod deployment failed!'
                  sh 'kubectl get pods | grep simple-test-pod || echo "Pod not found"'
              }
          }
      }
          </script>
          <sandbox>true</sandbox>
        </definition>
        <triggers/>
        <disabled>false</disabled>
      </flow-definition>
    status_code: [200, 400]
  register: create_job_result
  failed_when: false

- name: "Display Jenkins job creation result"
  ansible.builtin.debug:
    msg: |
      Jenkins job creation result:
      Status Code: {{ create_job_result.status }}
      {% if create_job_result.status == 200 %}
      Job 'simple-pod-deployment' created successfully!
      {% elif create_job_result.status == 400 %}
      Job may already exist or creation failed.
      {% else %}
      Job creation failed with status: {{ create_job_result.status }}
      {% endif %}

- name: "Verify job was created"
  ansible.builtin.shell: |
    java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_default_ipv4.address }}:8080 -auth admin:{{ jenkins_initial_password.stdout }} list-jobs | grep simple-pod-deployment
  register: job_verification
  failed_when: false

- name: "Display job verification result"
  ansible.builtin.debug:
    msg: |
      Job verification:
      {{ job_verification.stdout }}
      {% if job_verification.rc == 0 %}
      Job 'simple-pod-deployment' found in Jenkins!
      {% else %}
      Job 'simple-pod-deployment' not found in Jenkins.
      {% endif %}

- name: "Trigger Jenkins pipeline using REST API"
  ansible.builtin.uri:
    url: "http://{{ ansible_default_ipv4.address }}:8080/job/simple-pod-deployment/build"
    method: POST
    user: admin
    password: "{{ jenkins_initial_password.stdout }}"
    status_code: [200, 201, 302]
  register: trigger_build_result
  failed_when: false

- name: "Display pipeline trigger result"
  ansible.builtin.debug:
    msg: |
      Pipeline trigger result:
      Status Code: {{ trigger_build_result.status }}
      {% if trigger_build_result.status in [200, 201, 302] %}
      Pipeline 'simple-pod-deployment' triggered successfully!
      {% else %}
      Pipeline trigger failed with status: {{ trigger_build_result.status }}
      {% endif %}

- name: "Wait for build to start"
  ansible.builtin.pause:
    seconds: 10

- name: "Get latest build status"
  ansible.builtin.shell: |
    java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_default_ipv4.address }}:8080 -auth admin:{{ jenkins_initial_password.stdout }} get-job "simple-pod-deployment"
  register: job_status
  failed_when: false

- name: "Display Jenkins access information"
  ansible.builtin.debug:
    msg: |
      Jenkins Pipeline Setup Complete!
      
      Jenkins URL: http://{{ ansible_default_ipv4.address }}:8080
      Job Name: simple-pod-deployment
      
      To view the pipeline:
      1. Go to http://{{ ansible_default_ipv4.address }}:8080
      2. Login with admin/{{ jenkins_initial_password.stdout }}
      3. Click on 'simple-pod-deployment' job
      4. View the build progress and logs
      
      To manually trigger the pipeline:
      java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_default_ipv4.address }}:8080 -auth admin:{{ jenkins_initial_password.stdout }} build "simple-pod-deployment" 