---
- name: "Reset any existing Kubernetes installation on worker nodes"
  ansible.builtin.shell: |
    kubeadm reset -f
    rm -rf /etc/kubernetes/pki /etc/kubernetes/manifests /var/lib/etcd
    systemctl restart containerd
  loop: "{{ groups['k8s-worker'] }}"
  ignore_errors: true

- name: "Create /etc/kubernetes/manifests directory on worker nodes"
  ansible.builtin.file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: "Join Worker node"
  ansible.builtin.shell: |
    kubeadm join {{ endpoint_lb }}:{{ control_plane_port }} \
      --token {{ hostvars[groups['boostrap-node'][0]]['join_token'] }} \
      --discovery-token-ca-cert-hash {{ hostvars[groups['boostrap-node'][0]]['discovery_token_ca_cert_hash'] }}
  loop: "{{ groups['k8s-worker'] }}"