---
- name: "Install Calico Tigera Operator"
  ansible.builtin.shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
  ignore_errors: yes

- name: "Wait for Tigera Operator to be ready"
  ansible.builtin.shell: |
    kubectl wait --for=condition=available deployment/tigera-operator -n tigera-operator --timeout=300s
  ignore_errors: yes

- name: "Install Calico CNI"
  ansible.builtin.shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
  ignore_errors: yes

- name: "Wait for Calico pods to be ready"
  ansible.builtin.shell: |
    kubectl wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s
  ignore_errors: yes

- name: "Wait for Calico controller to be ready"
  ansible.builtin.shell: |
    kubectl wait --for=condition=ready pod -l k8s-app=calico-kube-controllers -n kube-system --timeout=300s
  ignore_errors: yes

- name: "Check Calico installation"
  ansible.builtin.shell: |
    kubectl get pods -n kube-system | grep calico
  register: calico_status
  changed_when: false

- name: "Display Calico status"
  ansible.builtin.debug:
    msg: "{{ calico_status.stdout }}"